name: Maven Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0670d37ba1d09fecf5018ace93a4e5727f7b5772

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Make mvnw executable
        run: chmod +x ./backend/backend/mvnw

      - name: Run tests with verbose output
        working-directory: ./backend/backend  # Adjusted path
        run: chmod +x mvnw && ./mvnw -X test
