name: Maven Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Trin 1: Hent kildekoden fra git ind i GitHub Actions VM'en
      - uses: actions/checkout@v3

      # Trin 2: Installér Java i GitHub Actions VM'en
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      # Trin 3: Test koden! (I den rigtige mappe...)
      - name: Run tests
        working-directory: ./backend
        run: ./mvnw test
